# Generated by Django 5.0.6 on 2024-05-11 16:36

import django.db.models.deletion
import django_countries.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CareerLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('city_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='EducationalLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=400)),
            ],
        ),
        migrations.CreateModel(
            name='EmploymentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='JobCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('cat_image', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='MonthlySalary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='JobAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_pic', models.ImageField(default='img/avata/avataars.png', upload_to='media')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_link', models.CharField(blank=True, max_length=200, null=True)),
                ('company_name', models.CharField(default=None, max_length=300)),
                ('company_logo', models.ImageField(blank=True, null=True, upload_to='')),
                ('hide_company_name', models.BooleanField()),
                ('job_title', models.CharField(default=None, max_length=200)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('gender', models.BooleanField(blank=True, choices=[(None, 'Any'), (True, 'male'), (False, 'female')], null=True)),
                ('location', models.CharField(blank=True, max_length=50, null=True)),
                ('nationality', django_countries.fields.CountryField(blank=True, max_length=746, multiple=True)),
                ('remote', models.BooleanField(default=False)),
                ('years_of_experience', models.IntegerField(default=1)),
                ('skill_set1', models.CharField(max_length=300)),
                ('skill_set2', models.CharField(blank=True, max_length=300, null=True)),
                ('skill_set3', models.CharField(blank=True, max_length=300, null=True)),
                ('cv_required', models.BooleanField(default=False)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('salary', models.CharField(blank=True, max_length=50, null=True)),
                ('featuredjobs', models.BooleanField(default=False)),
                ('career_level', models.ManyToManyField(to='myjob.careerlevel')),
                ('category', models.ManyToManyField(to='myjob.jobcategory')),
                ('city', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='myjob.city')),
                ('educational_level', models.ManyToManyField(to='myjob.educationallevel')),
                ('employment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myjob.employmenttype')),
                ('job_admin', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='myjob.jobadmin')),
                ('monthly_salary', models.ManyToManyField(blank=True, null=True, to='myjob.monthlysalary')),
            ],
        ),
    ]
