# Generated by Django 5.0.6 on 2024-05-14 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myjob', '0002_jobs_job_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobs',
            name='monthly_salary',
            field=models.ManyToManyField(to='myjob.monthlysalary'),
        ),
    ]
